name: Docker Image Push

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.export.outputs.tag }}
    permissions:
      contents: read
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Log into DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/nginx-with-amazing-webpage
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Export image tags
        id: export
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  
  deploy:
    needs: build
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo with k8s manifests
        uses: actions/checkout@v6
        with:
          repository: ritehist/devops-diploma-kube
          ref: 'main'
          sparse-checkout: src/app-config
      
      - name: Get inventory.ini
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: inventory.ini
          repository: RiteHist/devops-diploma
          run-id: ${{ vars.TERRAFORM_RUN_ID }}
      
      - name: Parse controller and NAT IPs
        id: ips
        run: |
          NAT_IP=$(awk '/\[bastion\]/ {flag=1; next} flag && /ansible_host=/ {gsub(/.*=/,""); print; flag=0}' inventory.ini)
          CONTROLLER_IP=$(awk '/\[kube_control_plane\]/ {flag=1; next} flag && /ansible_host=/ {gsub(/.*=/,""); print; flag=0}' inventory.ini)
          echo "nat_ip=$NAT_IP" >> $GITHUB_OUTPUT
          echo "controller_ip=$CONTROLLER_IP" >> $GITHUB_OUTPUT
        
      
      - name: Create ssh key file
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 << 'EOF'
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          cat > ~/.ssh/config << 'EOF'
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
      
      - name: Add key to ssh agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519

      - name: Copy admin.conf from controller
        env:
          NAT_IP: ${{ steps.ips.outputs.nat_ip }}
          CONTROLLER_IP: ${{ steps.ips.outputs.controller_ip }}
        run: |
          ssh -o ProxyJump=${{ vars.VM_USERNAME }}@${NAT_IP} ${{ vars.VM_USERNAME }}@${CONTROLLER_IP} "sudo cat /etc/kubernetes/admin.conf" > admin.conf
      
      - name: Change server in admin.conf
        env:
          NAT_IP: ${{ steps.ips.outputs.nat_ip }}
        run: |
          sed -i "s|server: https://[^:]*:6443|server: https://${NAT_IP}:6443|" admin.conf
      
      - name: Get admin.conf content
        id: kubeconfig
        run: |
          CONFIG_CONTENT=$(cat admin.conf | base64 -w 0)
          echo "::add-mask::$CONFIG_CONTENT"
          echo "kubeconfig=$CONFIG_CONTENT" >> $GITHUB_OUTPUT
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Set kube context
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      
      - name: Deploy manifest
        uses: Azure/k8s-deploy@v5
        with:
          manifests: src/app-config/1-deployment.yaml
          images: ${{ needs.build.outputs.image_tag }}
          action: deploy
